### ISSUE TITLE
Cannot find module 'js-yaml'

### ISSUE THREAD

**Issue by alpanchino** [udondan/cdk-ssm-document#18]
For Python import of the Document throws next exception:
-------------------------------------------------------------------------------------------
PS C:\Users\XXX\cdk-ssm> cdk ls
jsii.errors.JavaScriptError: 
  internal/modules/cjs/loader.js:638
      throw err;
      ^

  **Error: Cannot find module 'js-yaml'**
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
      at Function.Module._load (internal/modules/cjs/loader.js:562:25)
      at Module.require (internal/modules/cjs/loader.js:692:17)
      at require (internal/modules/cjs/helpers.js:25:18)
      at Object.<anonymous> (C:\Users\XXX\AppData\Local\Temp\jsii-kernel-w7ZNRI\node_modules\cdk-ssm-document\lib\index.js:11:14)
      at Module._compile (internal/modules/cjs/loader.js:778:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
      at Module.load (internal/modules/cjs/loader.js:653:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
      at Module._load (internal/modules/cjs/loader.js:585:3)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\XXX\cdk-ssm\app.py", line 6, in <module>
    from cdk_ssm.cdk_ssm_stack import CdkSsmStack
  File "C:\Users\XXX\cdk-ssm\cdk_ssm\cdk_ssm_stack.py", line 5, in <module>
    from cdk_ssm_document import Document
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\cdk_ssm_document\__init__.py", line 297, in <module>
    from ._jsii import *
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\cdk_ssm_document\_jsii\__init__.py", line 18, in <module>
    __jsii_assembly__ = jsii.JSIIAssembly.load(
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\jsii\_runtime.py", line 43, in load
    _kernel.load(assembly.name, assembly.version, os.fspath(assembly_path))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\jsii\_kernel\__init__.py", line 254, in load
    self.provider.load(LoadRequest(name=name, version=version, tarball=tarball))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\jsii\_kernel\providers\process.py", line 338, in load
    return self._process.send(request, LoadResponse)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\jsii\_kernel\providers\process.py", line 326, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: Cannot find module 'js-yaml'

---------------------------------------------------------------------------------------------------------------------------

PS C:\Users\XXX\cdk-ssm> npm list -g
C:\Users\XXX\AppData\Roaming\npm
+-- aws-cdk@1.101.0
| +-- @aws-cdk/cloud-assembly-schema@1.101.0
| | +-- jsonschema@1.4.0
| | `-- semver@7.3.5 deduped
| +-- @aws-cdk/cloudformation-diff@1.101.0
| | +-- @aws-cdk/cfnspec@1.101.0
| | | `-- md5@2.3.0
| | |   +-- charenc@0.0.2
| | |   +-- crypt@0.0.2
| | |   `-- is-buffer@1.1.6
| | +-- colors@1.4.0 deduped
| | +-- diff@5.0.0
| | +-- fast-deep-equal@3.1.3
| | +-- string-width@4.2.2
| | | +-- emoji-regex@8.0.0
| | | +-- is-fullwidth-code-point@3.0.0
| | | `-- strip-ansi@6.0.0 deduped
| | `-- table@6.3.2
| |   +-- ajv@8.0.2 deduped
| |   +-- is-boolean-object@1.1.0 deduped
| |   +-- is-number-object@1.0.4 deduped
| |   +-- is-string@1.0.5 deduped
| |   +-- lodash.clonedeep@4.5.0 deduped
| |   +-- lodash.flatten@4.4.0 deduped
| |   +-- lodash.truncate@4.4.2 deduped
| |   +-- slice-ansi@4.0.0 deduped
| |   `-- string-width@4.2.2 deduped
| +-- @aws-cdk/cx-api@1.101.0
| | +-- @aws-cdk/cloud-assembly-schema@1.101.0 deduped
| | `-- semver@7.3.5 deduped
| +-- @aws-cdk/region-info@1.101.0
| +-- archiver@5.3.0
| | +-- archiver-utils@2.1.0
| | | +-- glob@7.1.6 deduped
| | | +-- graceful-fs@4.2.6 deduped
| | | +-- lazystream@1.0.0
| | | | `-- readable-stream@2.3.7
| | | |   +-- core-util-is@1.0.2 deduped
| | | |   +-- inherits@2.0.4 deduped
| | | |   +-- isarray@1.0.0 deduped
| | | |   +-- process-nextick-args@2.0.1 deduped
| | | |   +-- safe-buffer@5.1.2 deduped
| | | |   +-- string_decoder@1.1.1 deduped
| | | |   `-- util-deprecate@1.0.2 deduped
| | | +-- lodash.defaults@4.2.0
| | | +-- lodash.difference@4.5.0
| | | +-- lodash.flatten@4.4.0 deduped
| | | +-- lodash.isplainobject@4.0.6
| | | +-- lodash.union@4.6.0
| | | +-- normalize-path@3.0.0
| | | `-- readable-stream@2.3.7
| | |   +-- core-util-is@1.0.2
| | |   +-- inherits@2.0.4 deduped
| | |   +-- isarray@1.0.0 deduped
| | |   +-- process-nextick-args@2.0.1
| | |   +-- safe-buffer@5.1.2
| | |   +-- string_decoder@1.1.1
| | |   | `-- safe-buffer@5.1.2 deduped
| | |   `-- util-deprecate@1.0.2 deduped
| | +-- async@3.2.0
| | +-- buffer-crc32@0.2.13
| | +-- readable-stream@3.6.0
| | | +-- inherits@2.0.4 deduped
| | | +-- string_decoder@1.3.0
| | | | `-- safe-buffer@5.2.1
| | | `-- util-deprecate@1.0.2
| | +-- readdir-glob@1.1.1
| | | `-- minimatch@3.0.4 deduped
| | +-- tar-stream@2.2.0
| | | +-- bl@4.1.0
| | | | +-- buffer@5.7.1
| | | | | +-- base64-js@1.5.1 deduped
| | | | | `-- ieee754@1.2.1
| | | | +-- inherits@2.0.4 deduped
| | | | `-- readable-stream@3.6.0 deduped
| | | +-- end-of-stream@1.4.4
| | | | `-- once@1.4.0 deduped
| | | +-- fs-constants@1.0.0
| | | +-- inherits@2.0.4 deduped
| | | `-- readable-stream@3.6.0 deduped
| | `-- zip-stream@4.1.0
| |   +-- archiver-utils@2.1.0 deduped
| |   +-- compress-commons@4.1.0
| |   | +-- buffer-crc32@0.2.13 deduped
| |   | +-- crc32-stream@4.0.2
| |   | | +-- crc-32@1.2.0
| |   | | | +-- exit-on-epipe@1.0.1
| |   | | | `-- printj@1.1.2
| |   | | `-- readable-stream@3.6.0 deduped
| |   | +-- normalize-path@3.0.0 deduped
| |   | `-- readable-stream@3.6.0 deduped
| |   `-- readable-stream@3.6.0 deduped
| +-- aws-sdk@2.866.0
| | +-- buffer@4.9.2
| | | +-- base64-js@1.5.1
| | | +-- ieee754@1.2.1
| | | `-- isarray@1.0.0
| | +-- events@1.1.1
| | +-- ieee754@1.1.13
| | +-- jmespath@0.15.0
| | +-- querystring@0.2.0
| | +-- sax@1.2.1
| | +-- url@0.10.3
| | | +-- punycode@1.3.2
| | | `-- querystring@0.2.0 deduped
| | +-- uuid@3.3.2
| | `-- xml2js@0.4.19
| |   +-- sax@1.2.4
| |   `-- xmlbuilder@9.0.7
| +-- camelcase@6.2.0
| +-- cdk-assets@1.101.0
| | +-- @aws-cdk/cloud-assembly-schema@1.101.0 deduped
| | +-- @aws-cdk/cx-api@1.101.0 deduped
| | +-- archiver@5.3.0 deduped
| | +-- aws-sdk@2.866.0 deduped
| | +-- glob@7.1.6 deduped
| | `-- yargs@16.2.0 deduped
| +-- colors@1.4.0
| +-- decamelize@5.0.0
| +-- fs-extra@9.1.0
| | +-- at-least-node@1.0.0
| | +-- graceful-fs@4.2.6
| | +-- jsonfile@6.1.0
| | | +-- graceful-fs@4.2.6 deduped
| | | `-- universalify@2.0.0 deduped
| | `-- universalify@2.0.0
| +-- glob@7.1.6
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | +-- once@1.4.0 deduped
| | | `-- wrappy@1.0.2
| | +-- inherits@2.0.4
| | +-- minimatch@3.0.4 deduped
| | +-- once@1.4.0
| | | `-- wrappy@1.0.2 deduped
| | `-- path-is-absolute@1.0.1
| +-- json-diff@0.5.4
| | +-- cli-color@0.1.7
| | | `-- es5-ext@0.8.2
| | +-- difflib@0.2.4
| | | `-- heap@0.2.6
| | `-- dreamopt@0.6.0
| |   `-- wordwrap@1.0.0
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.11
| |   +-- balanced-match@1.0.0
| |   `-- concat-map@0.0.1
| +-- promptly@3.2.0
| | `-- read@1.0.7
| |   `-- mute-stream@0.0.8
| +-- proxy-agent@4.0.1
| | +-- agent-base@6.0.2
| | | `-- debug@4.3.1 deduped
| | +-- debug@4.3.1
| | | `-- ms@2.1.2
| | +-- http-proxy-agent@4.0.1
| | | +-- @tootallnate/once@1.1.2
| | | +-- agent-base@6.0.2 deduped
| | | `-- debug@4.3.1 deduped
| | +-- https-proxy-agent@5.0.0
| | | +-- agent-base@6.0.2 deduped
| | | `-- debug@4.3.1 deduped
| | +-- lru-cache@5.1.1
| | | `-- yallist@3.1.1
| | +-- pac-proxy-agent@4.1.0
| | | +-- @tootallnate/once@1.1.2 deduped
| | | +-- agent-base@6.0.2 deduped
| | | +-- debug@4.3.1 deduped
| | | +-- get-uri@3.0.2
| | | | +-- @tootallnate/once@1.1.2 deduped
| | | | +-- data-uri-to-buffer@3.0.1
| | | | +-- debug@4.3.1 deduped
| | | | +-- file-uri-to-path@2.0.0
| | | | +-- fs-extra@8.1.0
| | | | | +-- graceful-fs@4.2.6 deduped
| | | | | +-- jsonfile@4.0.0
| | | | | | `-- graceful-fs@4.2.6 deduped
| | | | | `-- universalify@0.1.2
| | | | `-- ftp@0.3.10
| | | |   +-- readable-stream@1.1.14
| | | |   | +-- core-util-is@1.0.2 deduped
| | | |   | +-- inherits@2.0.4 deduped
| | | |   | +-- isarray@0.0.1
| | | |   | `-- string_decoder@0.10.31
| | | |   `-- xregexp@2.0.0
| | | +-- http-proxy-agent@4.0.1 deduped
| | | +-- https-proxy-agent@5.0.0 deduped
| | | +-- pac-resolver@4.2.0
| | | | +-- degenerator@2.2.0
| | | | | +-- ast-types@0.13.4
| | | | | | `-- tslib@2.1.0
| | | | | +-- escodegen@1.14.3
| | | | | | +-- esprima@4.0.1 deduped
| | | | | | +-- estraverse@4.3.0
| | | | | | +-- esutils@2.0.3
| | | | | | +-- optionator@0.8.3
| | | | | | | +-- deep-is@0.1.3
| | | | | | | +-- fast-levenshtein@2.0.6
| | | | | | | +-- levn@0.3.0
| | | | | | | | +-- prelude-ls@1.1.2 deduped
| | | | | | | | `-- type-check@0.3.2 deduped
| | | | | | | +-- prelude-ls@1.1.2
| | | | | | | +-- type-check@0.3.2
| | | | | | | | `-- prelude-ls@1.1.2 deduped
| | | | | | | `-- word-wrap@1.2.3
| | | | | | `-- source-map@0.6.1 deduped
| | | | | `-- esprima@4.0.1
| | | | +-- ip@1.1.5
| | | | `-- netmask@2.0.1
| | | +-- raw-body@2.4.1
| | | | +-- bytes@3.1.0
| | | | +-- http-errors@1.7.3
| | | | | +-- depd@1.1.2
| | | | | +-- inherits@2.0.4 deduped
| | | | | +-- setprototypeof@1.1.1
| | | | | +-- statuses@1.5.0
| | | | | `-- toidentifier@1.0.0
| | | | +-- iconv-lite@0.4.24
| | | | | `-- safer-buffer@2.1.2
| | | | `-- unpipe@1.0.0
| | | `-- socks-proxy-agent@5.0.0 deduped
| | +-- proxy-from-env@1.1.0
| | `-- socks-proxy-agent@5.0.0
| |   +-- agent-base@6.0.2 deduped
| |   +-- debug@4.3.1 deduped
| |   `-- socks@2.6.0
| |     +-- ip@1.1.5 deduped
| |     `-- smart-buffer@4.1.0
| +-- semver@7.3.5
| | `-- lru-cache@6.0.0
| |   `-- yallist@4.0.0
| +-- source-map-support@0.5.19
| | +-- buffer-from@1.1.1
| | `-- source-map@0.6.1
| +-- table@6.1.0
| | +-- ajv@8.0.2
| | | +-- fast-deep-equal@3.1.3 deduped
| | | +-- json-schema-traverse@1.0.0
| | | +-- require-from-string@2.0.2
| | | `-- uri-js@4.4.1
| | |   `-- punycode@2.1.1
| | +-- is-boolean-object@1.1.0
| | | `-- call-bind@1.0.2
| | |   +-- function-bind@1.1.1
| | |   `-- get-intrinsic@1.1.1
| | |     +-- function-bind@1.1.1 deduped
| | |     +-- has@1.0.3
| | |     | `-- function-bind@1.1.1 deduped
| | |     `-- has-symbols@1.0.2
| | +-- is-number-object@1.0.4
| | +-- is-string@1.0.5
| | +-- lodash.clonedeep@4.5.0
| | +-- lodash.flatten@4.4.0
| | +-- lodash.truncate@4.4.2
| | +-- slice-ansi@4.0.0
| | | +-- ansi-styles@4.3.0 deduped
| | | +-- astral-regex@2.0.0
| | | `-- is-fullwidth-code-point@3.0.0 deduped
| | `-- string-width@4.2.2 deduped
| +-- uuid@8.3.2
| +-- wrap-ansi@7.0.0
| | +-- ansi-styles@4.3.0
| | | `-- color-convert@2.0.1
| | |   `-- color-name@1.1.4
| | +-- string-width@4.2.2 deduped
| | `-- strip-ansi@6.0.0
| |   `-- ansi-regex@5.0.0
| +-- yaml@1.10.2
| `-- yargs@16.2.0
|   +-- cliui@7.0.4
|   | +-- string-width@4.2.2 deduped
|   | +-- strip-ansi@6.0.0 deduped
|   | `-- wrap-ansi@7.0.0 deduped
|   +-- escalade@3.1.1
|   +-- get-caller-file@2.0.5
|   +-- require-directory@2.1.1
|   +-- string-width@4.2.2 deduped
|   +-- y18n@5.0.5
|   `-- yargs-parser@20.2.7
**+-- js-yaml@4.1.0**
| `-- argparse@2.0.1

**Comment by udondan** [comment]
Thank you Oleksandr for bringing this to my attention. I just released v2.2.1 which includes the fix.
