### ISSUE TITLE
Add support for Document Attachments

### ISSUE THREAD

**Issue by zendern** [udondan/cdk-ssm-document#21]
### Problem statement : 
Cannot create a SSM Document that can be used with AWS Distributor since attachments cannot be added to the definition. 

See an example of what the SSM Document looks like for a Distributor package using Cloudformation: 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ssm-document.html#aws-resource-ssm-document--examples--Create_a__Distributor_package

### Solution: 
* Update lib to allow for an optional Attachments property at the Document level
   * Also will likely want to create AttachmentSource child object https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_AttachmentsSource.html
* Update lambda when create/update is called to pass the Attachments if they are defined

Happy to create a PR to implement this.

**Comment by udondan** [comment]
> Happy to create a PR to implement this.

Sounds good! 👍🏼
