### ISSUE TITLE
Rollback can fail due to failed Document deletion

### ISSUE THREAD

**Issue by otterley** [udondan/cdk-ssm-document#28]
While instantiating a stack for the first time, my SSM document had an error in it that wasn't identified during the pre-deploy checks. During rollback, the Lambda function tried to delete the (non-existent) document anyway, and failed. 

The error message below suggests that the IAM policy forbade it -- most likely due to the `Condition` key in the policy -- but even if the `Condition` key wasn't there, the DeleteDocument call probably would have failed anyway because the document failed to create in the first place.

```
Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::xxxxxxxxx:assumed-role/xxxxxxxxxxxStack-CFN-Resource-Custom-SSM-Document/xxxxxxxxxxxxxxBuilderStack-CFN-Resource-Custom-SSM-Document is not authorized to perform: ssm:DeleteDocument on
resource: arn:aws:ssm:us-west-2:xxxxxxxxx:document/xxxxxxx because no identity-based policy allows the ssm:DeleteDocument action | Full error in CloudWatch 2022/03/24/[$LATEST]xxxxxxxxxxxxxx (RequestId:xxxxxxxxxxxx)
```

**Comment by udondan** [comment]
I'm going to deprecate this construct. A few weeks ago there was an [update](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/pull/173) to the native CloudFormation resource, which now finally supports updates.
