### ISSUE TITLE
Function name cannot be longer than 64 characters

### ISSUE THREAD

**Issue by kpeters-cbsi** [udondan/cdk-ssm-document#32]
In `ensureLambda()` you're creating a function whose name is constructed from the stack name and the resource type. If this name exceeds 64 characters, CDK throws an error.

Example:
```
export class StackWithAReallyRidiculouslyLongName extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) { 
    # ...
   new Document(this, 'Document', {
      # ...
   })
  }
}
```

[The function created in ensureLambda()](https://github.com/udondan/cdk-ssm-document/blob/d71298db6d7cd32d278e170c4eee5d7892f02ecb/lib/index.ts#L330) will construct a function name of `StackWithAReallyRidiculouslyLongName-CFN-Resource-Custom-SSM-Document`, which is longer than 64 characters.

**Comment by udondan** [comment]
I'm going to deprecate this construct. A few weeks ago there was an [update](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ssm/pull/173) to the native CloudFormation resource, which now finally supports updates.
