### ISSUE TITLE
Help building Lambda

### ISSUE THREAD

**Issue by xombiemp** [udondan/cdk-ssm-document#8]
Can you give some more instructions on the prerequisites required to run the lambda/build script for someone with no dev environment?

**Comment by xombiemp** [comment]
I was able to work it out.  For any other people who are not Node devs:

Install Node.js and npm (and zip if you need to)
Download and unpack the latest release from https://github.com/udondan/cdk-ssm-document/releases/latest
sudo npm install -g ts-node typescript
cd cdk-ssm-document-*/
npm install
cd lambda
./build

**Comment by udondan** [comment]
Oh man, so sorry I didn't respond. Read your message on the phone in the morning and then totally forgot about it when I was at the computer. Glad you figured it out and thanks for leaving the description here for other! 👍
